### ISSUE TITLE
(6891) Service error: . Code=undefined. Stack: ServiceError

### ISSUE THREAD

**Issue by bandimuc** [marc2016/ioBroker.panasonic-comfort-cloud#24]
Hi,
I need your support, somehow this adapter reports issues even the adapter itself is connected and green. After installation I get following error log:

panasonic-comfort-cloud.0	2021-08-06 15:15:51.411	error	at processTicksAndRejections (internal/process/task_queues.js:97:5)
panasonic-comfort-cloud.0	2021-08-06 15:15:51.411	error	at rejected (/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:6:65)
panasonic-comfort-cloud.0	2021-08-06 15:15:51.411	error	at Object.throw (/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:14:53)
panasonic-comfort-cloud.0	2021-08-06 15:15:51.411	error	at step (/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:33:23)
panasonic-comfort-cloud.0	2021-08-06 15:15:51.411	error	at ComfortCloudClient.<anonymous> (/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:98:30)
panasonic-comfort-cloud.0	2021-08-06 15:15:51.411	error	at ComfortCloudClient.handleError (/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:176:15)
panasonic-comfort-cloud.0	2021-08-06 15:15:51.411	error	at new ServiceError (/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/model/ServiceError.js:20:28)
panasonic-comfort-cloud.0	2021-08-06 15:15:51.411	error	(6891) Service error: . Code=undefined. Stack: ServiceError
panasonic-comfort-cloud.0	2021-08-06 15:15:50.104	info	(6891) starting. Version 1.2.3 in /opt/iobroker/node_modules/iobroker.panasonic-comfort-cloud, node: v12.22.4, js-controller: 3.3.15

after a while I get recurring error like this:

panasonic-comfort-cloud.0	2021-08-06 15:20:00.979	error	at processTicksAndRejections (internal/process/task_queues.js:97:5)
panasonic-comfort-cloud.0	2021-08-06 15:20:00.979	error	at rejected (/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:6:65)
panasonic-comfort-cloud.0	2021-08-06 15:20:00.979	error	at Object.throw (/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:14:53)
panasonic-comfort-cloud.0	2021-08-06 15:20:00.979	error	at step (/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:33:23)
panasonic-comfort-cloud.0	2021-08-06 15:20:00.979	error	at ComfortCloudClient.<anonymous> (/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:133:30)
panasonic-comfort-cloud.0	2021-08-06 15:20:00.979	error	at ComfortCloudClient.handleError (/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:176:15)
panasonic-comfort-cloud.0	2021-08-06 15:20:00.979	error	at new ServiceError (/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/model/ServiceError.js:20:28)
panasonic-comfort-cloud.0	2021-08-06 15:20:00.979	error	(6891) Service error: . Code=undefined. Stack: ServiceError

Do you have any hint what could be the root-cause of this issue ??

As we have a very high temperature this summer a quick fix would be highly appreciated ;)

Many thanks in advance

Cheers
bandimuc

**Comment by bandimuc** [comment]
sorry, I didn't realize that a new version was posted. With version 1.2.7 this issue has been fixed :)
