### ISSUE TITLE
Serice Error 401

### ISSUE THREAD

**Issue by Aprilia1982** [marc2016/ioBroker.panasonic-comfort-cloud#36]
Hi, since today (after updating the adapter) I don't get access to the panasonic services. 

`panasonic-comfort-cloud.0
2022-10-11 14:35:32.358	error	Service error: Request failed with status code 401. Code=undefined. Stack: ServiceError: Request failed with status code 401 at new ServiceError (/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/model/ServiceError.js:20:28) at ComfortCloudClient.handleError (/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:178:15) at ComfortCloudClient.<anonymous> (/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:100:30) at step (/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:33:23) at Object.throw (/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:14:53) at rejected (/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:6:65) at processTicksAndRejections (node:internal/process/task_queues:96:5)`

I tried different versions of the adapter. I also changed my password and sucessfully tried to log in into the adroid app. 

Is there any issue regarding the api?

**Comment by gunbigun** [comment]
same issue here since today

**Comment by marc2016** [comment]
Hi, there was an update of the app, so i had to update the adapter as well.
As @gunbigun  writes, version 2.0.6 is the new version. It takes some time until it is in the official iobroker repository. Please use the npm or GitHub installation meanwhile :-)

**Comment by Aprilia1982** [comment]
Thanks a lot. 2.0.6 works properly
