### ISSUE TITLE
Error: Cannot find module '/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/index.js'. Please verify that the package.json has a valid "main" entry

### ISSUE THREAD

**Issue by Hansi1989** [marc2016/ioBroker.panasonic-comfort-cloud#38]
Hallo ich wollte gestern meine Klimaanlage wieder hinzufügen, aber leider bekomme ich nach dem installieren diese Fehlermeldungen.
Ich habe auch den Adapter im Terminal probiert zum installieren dort bekomme ich die gleiche Fehlermeldung.

2022-11-01 06:39:38.046 - error: host.Homeassistent Caught by controller[0]: node:internal/modules/cjs/loader:401
2022-11-01 06:39:38.046 - error: host.Homeassistent Caught by controller[0]: throw err;
2022-11-01 06:39:38.046 - error: host.Homeassistent Caught by controller[0]: ^
2022-11-01 06:39:38.046 - error: host.Homeassistent Caught by controller[0]: Error: Cannot find module '/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/index.js'. Please verify that the package.json has a valid "main" entry
2022-11-01 06:39:38.046 - error: host.Homeassistent Caught by controller[0]: at tryPackage (node:internal/modules/cjs/loader:393:19)
2022-11-01 06:39:38.046 - error: host.Homeassistent Caught by controller[0]: at Function.Module._findPath (node:internal/modules/cjs/loader:606:18)
2022-11-01 06:39:38.046 - error: host.Homeassistent Caught by controller[0]: at Function.Module._resolveFilename (node:internal/modules/cjs/loader:971:27)
2022-11-01 06:39:38.047 - error: host.Homeassistent Caught by controller[0]: at Function.Module._load (node:internal/modules/cjs/loader:833:27)
2022-11-01 06:39:38.047 - error: host.Homeassistent Caught by controller[0]: at Module.require (node:internal/modules/cjs/loader:1057:19)
2022-11-01 06:39:38.047 - error: host.Homeassistent Caught by controller[0]: at require (node:internal/modules/cjs/helpers:103:18)
2022-11-01 06:39:38.047 - error: host.Homeassistent Caught by controller[0]: at Object. (/opt/iobroker/node_modules/iobroker.panasonic-comfort-cloud/build/main.js:21:45)
2022-11-01 06:39:38.047 - error: host.Homeassistent Caught by controller[0]: at Module._compile (node:internal/modules/cjs/loader:1155:14)
2022-11-01 06:39:38.047 - error: host.Homeassistent Caught by controller[0]: at Object.Module._extensions..js (node:internal/modules/cjs/loader:1209:10)
2022-11-01 06:39:38.047 - error: host.Homeassistent Caught by controller[0]: at Module.load (node:internal/modules/cjs/loader:1033:32) {
2022-11-01 06:39:38.047 - error: host.Homeassistent Caught by controller[0]: code: 'MODULE_NOT_FOUND',
2022-11-01 06:39:38.047 - error: host.Homeassistent Caught by controller[0]: path: '/opt/iobroker/node_modules/panasonic-comfort-cloud-client/package.json',
2022-11-01 06:39:38.047 - error: host.Homeassistent Caught by controller[0]: requestPath: 'panasonic-comfort-cloud-client'
2022-11-01 06:39:38.047 - error: host.Homeassistent Caught by controller[0]: }
2022-11-01 06:39:38.047 - error: host.Homeassistent instance system.adapter.panasonic-comfort-cloud.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
2022-11-01 06:39:38.047 - info: host.Homeassistent Rebuild for adapter system.adapter.panasonic-comfort-cloud.0 not successful in 3 tries. Adapter will not be restarted again. Please execute "npm install --production" in adapter directory manually.

**Comment by marc2016** [comment]
Guten Morgen,

kannst du den Adapter einmal komplett deinstallieren über die ioBroker Admin Oberfläche?
Danach solltest Du ihn auch darüber wieder neuinstallieren können. Es scheinen nicht alle Abhängigkeiten installiert worden zu sein.

**Comment by Hansi1989** [comment]
Hallo Marc,

Ich habe den Adapter deinstalliert und neu installiert. Aber ohne Erfolg. Jetz bekomme ich noch eine Warnung zu den Errors im Protokoll dazu.


2022-11-01 17:13:11.348 - error: host.Homeassistent Caught by controller[0]: node:internal/modules/cjs/loader:401
2022-11-01 17:13:11.348 - error: host.Homeassistent Caught by controller[0]: throw err;
2022-11-01 17:13:11.348 - error: host.Homeassistent Caught by controller[0]: ^
2022-11-01 17:13:11.348 - error: host.Homeassistent Caught by controller[0]: Error: Cannot find module '/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/index.js'. Please verify that the package.json has a valid "main" entry
2022-11-01 17:13:11.348 - error: host.Homeassistent Caught by controller[0]: at tryPackage (node:internal/modules/cjs/loader:393:19)
2022-11-01 17:13:11.348 - error: host.Homeassistent Caught by controller[0]: at Function.Module._findPath (node:internal/modules/cjs/loader:606:18)
2022-11-01 17:13:11.349 - error: host.Homeassistent Caught by controller[0]: at Function.Module._resolveFilename (node:internal/modules/cjs/loader:971:27)
2022-11-01 17:13:11.349 - error: host.Homeassistent Caught by controller[0]: at Function.Module._load (node:internal/modules/cjs/loader:833:27)
2022-11-01 17:13:11.349 - error: host.Homeassistent Caught by controller[0]: at Module.require (node:internal/modules/cjs/loader:1057:19)
2022-11-01 17:13:11.349 - error: host.Homeassistent Caught by controller[0]: at require (node:internal/modules/cjs/helpers:103:18)
2022-11-01 17:13:11.349 - error: host.Homeassistent Caught by controller[0]: at Object. (/opt/iobroker/node_modules/iobroker.panasonic-comfort-cloud/build/main.js:21:45)
2022-11-01 17:13:11.349 - error: host.Homeassistent Caught by controller[0]: at Module._compile (node:internal/modules/cjs/loader:1155:14)
2022-11-01 17:13:11.349 - error: host.Homeassistent Caught by controller[0]: at Object.Module._extensions..js (node:internal/modules/cjs/loader:1209:10)
2022-11-01 17:13:11.349 - error: host.Homeassistent Caught by controller[0]: at Module.load (node:internal/modules/cjs/loader:1033:32) {
2022-11-01 17:13:11.349 - error: host.Homeassistent Caught by controller[0]: code: 'MODULE_NOT_FOUND',
2022-11-01 17:13:11.349 - error: host.Homeassistent Caught by controller[0]: path: '/opt/iobroker/node_modules/panasonic-comfort-cloud-client/package.json',
2022-11-01 17:13:11.349 - error: host.Homeassistent Caught by controller[0]: requestPath: 'panasonic-comfort-cloud-client'
2022-11-01 17:13:11.349 - error: host.Homeassistent Caught by controller[0]: }
2022-11-01 17:13:11.350 - error: host.Homeassistent instance system.adapter.panasonic-comfort-cloud.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
2022-11-01 17:13:11.350 - info: host.Homeassistent Adapter system.adapter.panasonic-comfort-cloud.0 needs rebuild and will be restarted afterwards.
2022-11-01 17:13:11.350 - info: host.Homeassistent system.adapter.panasonic-comfort-cloud.0 will be rebuilt
**2022-11-01 17:13:11.350 - warn: host.Homeassistent adapter "panasonic-comfort-cloud" seems to be installed for a different version of Node.js. Trying to rebuild it... 3 attempt**


PlatformBetriebssystem:linux
Architektur:x64
CPUs:2
Geschwindigkeit:2001 MHz
Modell:Intel(R) Celeron(R) J4025 CPU @ 2.00GHz
RAM:5.6 GB
System-Betriebszeit:11 T. 21:17:52
Node.js:v16.18.0
time:1667318973455
timeOffset:-60
Adapter-Anzahl:443
NPM:8.19.2
Datenträgergröße:3572.6 GB
Freier Festplattenspeicher:3135.6 GB
Betriebszeit:06:52:38
Aktive Instanzen:15
Pfad:/opt/iobroker/
aktiv:true
_nodeCurrent:16.18.0
_nodeNewest:16.18.0
_nodeNewestNext:16.18.0
_npmCurrent:8.19.2
_npmNewest:8.19.2
_npmNewestNext:8.19.2

**Comment by Hansi1989** [comment]
$ iobroker url marc2016/ioBroker.panasonic-comfort-cloud --host Homeassistent --debug

install marc2016/ioBroker.panasonic-comfort-cloud

NPM version: 8.19.2

Installing marc2016/ioBroker.panasonic-comfort-cloud... (System call)

added 3 packages in 18s

80 packages are looking for funding run `npm fund` for details

upload [4] panasonic-comfort-cloud.admin /opt/iobroker/node_modules/iobroker.panasonic-comfort-cloud/admin/admin.d.ts admin.d.ts video/mp2t

upload [3] panasonic-comfort-cloud.admin /opt/iobroker/node_modules/iobroker.panasonic-comfort-cloud/admin/index_m.html index_m.html text/html

upload [2] panasonic-comfort-cloud.admin /opt/iobroker/node_modules/iobroker.panasonic-comfort-cloud/admin/panasonic-comfort-cloud.png panasonic-comfort-cloud.png image/png

upload [1] panasonic-comfort-cloud.admin /opt/iobroker/node_modules/iobroker.panasonic-comfort-cloud/admin/style.css style.css text/css

upload [0] panasonic-comfort-cloud.admin /opt/iobroker/node_modules/iobroker.panasonic-comfort-cloud/admin/words.js words.js application/javascript

Process exited with code 0


das ist die Installation aber leider immer noch ohne Erfolg

Lg Hansi

**Comment by marc2016** [comment]
Guten Morgen Hansi,

aus irgendeinem Grund findet er das andere NPM Modul panasonic-comfort-cloud-client nicht. Ich glaube ich hatte das Problem schon mal, wenn panasonic-comfort-cloud-client manuell installiert worden ist. Vielleicht ist das bei Dir auch der Fall.

Führe mal bitte `npm uninstall panasonic-comfort-cloud-client` aus, auf dem ioBroker Host. 

Viele Grüße 
Marc

**Comment by Hansi1989** [comment]
Guten Morgen Marc,

Danke hab den Client deinstalliert und neu installiert nach ein paar Versuchung hat er die npm gefunden.

Das Problem wurde somit behoben. Danke nochmals.

Lg Hansi

**Comment by marc2016** [comment]
Super, dass es geklappt hat. Gerne! ☺️
