### ISSUE TITLE
Adapter startet nicht

### ISSUE THREAD

**Issue by Sneaker29** [marc2016/ioBroker.panasonic-comfort-cloud#39]
Hallo,

bei mir will der Adapter einfach nicht auf grün bleiben. Vermutlich mache ich was falsch, aber ich weiß nicht was. Ich bekomme im Protokoll immer diese Meldungen:

state panasonic-comfort-cloud.0.info.connection changed: true (ack = true)

state panasonic-comfort-cloud.0.info.connection changed: false (ack = true)

Service error: Request failed with status code 500. Code=undefined. Stack: ServiceError: Request failed with status code 500 at new ServiceError (/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/model/ServiceError.js:20:28) at ComfortCloudClient.handleError (/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:178:15) at ComfortCloudClient.<anonymous> (/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:165:30) at step (/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:33:23) at Object.throw (/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:14:53) at rejected (/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:6:65) at processTicksAndRejections (internal/process/task_queues.js:97:5)

**Comment by marc2016** [comment]
Guten Morgen,

kannst Du bitte das Debug Logging von dem Adapter aktivieren und es dann nochmal versuchen?
Poste die Log-Ausgaben bitte hier nochmal. Danke!

Viele Grüße 
Marc

**Comment by Sneaker29** [comment]
Hallo Marc,

nachdem ich bei Adapter-Version manuell "1.17.0" eingetragen habe, bekomme ich leider trotzdem noch diese Meldung im Protokoll:

```
2023-04-08 14:02:00.157 - debug: panasonic-comfort-cloud.0 (16172) Redis Objects: Use Redis connection: 127.0.0.1:9001
--
2023-04-08 14:02:00.377 - debug: panasonic-comfort-cloud.0 (16172) Objects client ready ... initialize now
2023-04-08 14:02:00.390 - debug: panasonic-comfort-cloud.0 (16172) Objects create System PubSub Client
2023-04-08 14:02:00.394 - debug: panasonic-comfort-cloud.0 (16172) Objects create User PubSub Client
2023-04-08 14:02:00.995 - debug: panasonic-comfort-cloud.0 (16172) Objects client initialize lua scripts
2023-04-08 14:02:01.011 - debug: panasonic-comfort-cloud.0 (16172) Objects connected to redis: 127.0.0.1:9001
2023-04-08 14:02:01.171 - debug: panasonic-comfort-cloud.0 (16172) Redis States: Use Redis connection: 127.0.0.1:9000
2023-04-08 14:02:01.286 - debug: panasonic-comfort-cloud.0 (16172) States create System PubSub Client
2023-04-08 14:02:01.288 - debug: panasonic-comfort-cloud.0 (16172) States create User PubSub Client
2023-04-08 14:02:01.580 - debug: panasonic-comfort-cloud.0 (16172) States connected to redis: 127.0.0.1:9000
2023-04-08 14:02:02.513 - info: panasonic-comfort-cloud.0 (16172) starting. Version 2.1.0 in /opt/iobroker/node_modules/iobroker.panasonic-comfort-cloud, node: v18.15.0, js-controller: 4.0.23
2023-04-08 14:02:02.576 - debug: panasonic-comfort-cloud.0 (16172) Try to login with username iobroker@XXX.com.
2023-04-08 14:02:02.842 - info: panasonic-comfort-cloud.0 (16172) state panasonic-comfort-cloud.0.info.connection changed: false (ack = true)
2023-04-08 14:02:06.249 - info: panasonic-comfort-cloud.0 (16172) Login successful.
2023-04-08 14:02:06.252 - debug: panasonic-comfort-cloud.0 (16172) Create devices.
2023-04-08 14:02:06.290 - info: panasonic-comfort-cloud.0 (16172) state panasonic-comfort-cloud.0.info.connection changed: true (ack = true)
2023-04-08 14:02:07.273 - debug: panasonic-comfort-cloud.0 (16172) Device info from group CS-Z50XKEW+4887103421, Dachgeschoss.
2023-04-08 14:02:07.274 - debug: panasonic-comfort-cloud.0 (16172) Device info from group CS-Z35XKEW+4886911035, Schlafzimmer.
2023-04-08 14:02:08.116 - debug: panasonic-comfort-cloud.0 (16172) Try to handle error.
2023-04-08 14:02:08.118 - error: panasonic-comfort-cloud.0 (16172) Service error: Request failed with status code 500. Code=undefined. Stack: ServiceError: Request failed with status code 500
at new ServiceError (/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/model/ServiceError.js:20:28)
at ComfortCloudClient.handleError (/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:183:15)
at ComfortCloudClient. (/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:170:30)
at step (/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:33:23)
at Object.throw (/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:14:53)
at rejected (/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:6:65)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2023-04-08 14:02:08.131 - info: panasonic-comfort-cloud.0 (16172) state panasonic-comfort-cloud.0.info.connection changed: false (ack = true)
2023-04-08 14:02:08.996 - debug: panasonic-comfort-cloud.0 (16172) Device creation completed.
2023-04-08 14:02:08.997 - debug: panasonic-comfort-cloud.0 (16172) setupRefreshTimeout
2023-04-08 14:02:08.997 - debug: panasonic-comfort-cloud.0 (16172) refreshIntervalInMilliseconds=300000

```

**Comment by Sneaker29** [comment]
Hat sich erledigt. Inzwischen startet der Adapter einwandfrei. Bei mir war evtl. der Grund, dass eine Klimaanlage nicht mit dem Netz verbunden war.
