### ISSUE TITLE
Adapter verbindet nicht mehr

### ISSUE THREAD

**Issue by t1m02k16** [marc2016/ioBroker.panasonic-comfort-cloud#41]
Moin, der Adapter verbindet sich nicht mehr.... Bekomme folgende Fehlermeldung:

`Service error: Request failed with status code 401. Code=undefined. Stack: ServiceError: Request failed with status code 401 at new ServiceError (/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/model/ServiceError.js:20:28) at ComfortCloudClient.handleError (/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:183:15) at ComfortCloudClient.<anonymous> (/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:105:30) at step (/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:33:23) at Object.throw (/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:14:53) at rejected (/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:6:65) at processTicksAndRejections (internal/process/task_queues.js:95:5)`

**Comment by t1m02k16** [comment]
Fehler wurde unten schon beschrieben. Jetzt läuft es wieder! Vielen Dank @marc2016
