### ISSUE TITLE
Fehlermeldung bei zusätlicher Einbindung einer Wärmepumpe in die Cloud

### ISSUE THREAD

**Issue by JockelBln** [marc2016/ioBroker.panasonic-comfort-cloud#45]
Bei mir läuft der Adapter eigentlich sehr gut, vielen Dank dafür!

Nun habe ich zusätzlich zu den Klimas noch meine Aquarea Wärmepumpe mit in die Cloud aufgenommen.
In der App läuft das auch und ich kann alle Geräte steuern. Nur der Adapter funktioniert nun nicht mehr wie gewünscht und gibt nach dem Start folgendes aus:

> 2023-08-27 12:45:51.242 - info: host.iobroker "system.adapter.panasonic-comfort-cloud.0" enabled
2023-08-27 12:45:51.328 - info: host.iobroker instance system.adapter.panasonic-comfort-cloud.0 started with pid 626346
2023-08-27 12:45:52.177 - debug: panasonic-comfort-cloud.0 (626346) Redis Objects: Use Redis connection: 127.0.0.1:9001
2023-08-27 12:45:52.207 - debug: panasonic-comfort-cloud.0 (626346) Objects client ready ... initialize now
2023-08-27 12:45:52.210 - debug: panasonic-comfort-cloud.0 (626346) Objects create System PubSub Client
2023-08-27 12:45:52.211 - debug: panasonic-comfort-cloud.0 (626346) Objects create User PubSub Client
2023-08-27 12:45:52.243 - debug: panasonic-comfort-cloud.0 (626346) Objects client initialize lua scripts
2023-08-27 12:45:52.250 - debug: panasonic-comfort-cloud.0 (626346) Objects connected to redis: 127.0.0.1:9001
2023-08-27 12:45:52.267 - debug: panasonic-comfort-cloud.0 (626346) Redis States: Use Redis connection: 127.0.0.1:9000
2023-08-27 12:45:52.274 - debug: panasonic-comfort-cloud.0 (626346) States create System PubSub Client
2023-08-27 12:45:52.275 - debug: panasonic-comfort-cloud.0 (626346) States create User PubSub Client
2023-08-27 12:45:52.327 - debug: panasonic-comfort-cloud.0 (626346) States connected to redis: 127.0.0.1:9000
2023-08-27 12:45:52.483 - info: panasonic-comfort-cloud.0 (626346) starting. Version 2.2.0 in /opt/iobroker/node_modules/iobroker.panasonic-comfort-cloud, node: v18.16.1, js-controller: 4.0.24
2023-08-27 12:45:52.670 - info: panasonic-comfort-cloud.0 (626346) Loaded app version from GitHub: 1.18.2
2023-08-27 12:45:52.671 - debug: panasonic-comfort-cloud.0 (626346) Use AppVersion from Github 1.18.2.
2023-08-27 12:45:52.672 - debug: panasonic-comfort-cloud.0 (626346) Use default AppVersion.
2023-08-27 12:45:52.673 - debug: panasonic-comfort-cloud.0 (626346) Try to login with username user@mail.org.
2023-08-27 12:45:52.711 - info: panasonic-comfort-cloud.0 (626346) state panasonic-comfort-cloud.0.info.connection changed: false (ack = true)
2023-08-27 12:45:55.653 - info: panasonic-comfort-cloud.0 (626346) Login successful.
2023-08-27 12:45:55.653 - debug: panasonic-comfort-cloud.0 (626346) Create devices.
2023-08-27 12:45:55.664 - info: panasonic-comfort-cloud.0 (626346) state panasonic-comfort-cloud.0.info.connection changed: true (ack = true)
2023-08-27 12:45:58.951 - debug: panasonic-comfort-cloud.0 (626346) Try to handle error.
2023-08-27 12:45:58.952 - error: panasonic-comfort-cloud.0 (626346) Unknown error: TypeError: Cannot read properties of undefined (reading 'data'). Stack: TypeError: Cannot read properties of undefined (reading 'data')
at ComfortCloudClient.handleError (/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:180:42)
at ComfortCloudClient. (/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:141:30)
at step (/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:33:23)
at Object.next (/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:14:53)
at fulfilled (/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:5:58)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Gibt es eventuell eine Möglichkeit die Geräte unter einem Account laufen zu lassen, was für die Bedienung über die App einfacher wäre? Bisher habe ich die WP und die ACs in zwei verschiedenen Accounts, was am Handy nicht wirklich praktisch ist.

**Comment by marc2016** [comment]
Scheinbar versucht der Adapter Daten von dem Gerät abzurufen, die es nicht gibt. Den Fehler müsste ich abfangen, damit der Adapter danach weiterläuft.
