### ISSUE TITLE
Im Adapter werden die Geräte nicht angezeigt

### ISSUE THREAD

**Issue by Borchi2805** [marc2016/ioBroker.panasonic-comfort-cloud#51]
Hallo,

ich habe den aktuellen Adapter installiert. Er verbindet sich auch mit der Panasonic Cloud. Es werden aber keine Geräte in den Objekten angelegt.

Als Fehler kommt einmalig:

2023-09-29 19:11:43.813 - info: panasonic-comfort-cloud.1 (3096) state panasonic-comfort-cloud.1.info.connection changed: true (ack = true)
--
2023-09-29 19:11:44.423 - error: panasonic-comfort-cloud.1 (3096) Unknown error: TypeError: Cannot read properties of undefined (reading 'data'). Stack: TypeError: Cannot read properties of undefined (reading 'data')
at ComfortCloudClient.handleError (/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:180:42)
at ComfortCloudClient. (/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:141:30)
at step (/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:33:23)
at Object.next (/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:14:53)
at fulfilled (/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:5:58)
at processTicksAndRejections (node:internal/process/task_queues:96:5)

Gibt es da eine Erklärung?

**Comment by Skol6** [comment]
Konntest du das schon lösen?

**Comment by Borchi2805** [comment]
> Konntest du das schon lösen?

Leider nein. Es gab zwar jetzt ein Update, aber ich bekomme es nicht ans Laufen :(

**Comment by marc2016** [comment]
Hast Du vielleicht nur eine Wärmepumpe? Die funktionieren leider nicht mit dem Adapter.
