### ISSUE TITLE
Es werden keine Werte ausgelesen. 

### ISSUE THREAD

**Issue by hauthaler** [marc2016/ioBroker.panasonic-comfort-cloud#53]
Nachdem ich den Adapter erfolgreich eingebunden habe udn einen zweiten User für die Panasonic Cloud eingerichtet habe bekomme ich bei den Logs folgende Fehlermeldung. Ich habe iobroker über einen Docker auf meiner Synolgy NAS installieret und bisher bei keinem anderen Adapter diese Probleme.

Da ich die Daten sehr dringedn benötige hoffe ich auf schnelle Rückmeldung. --> Vielen Dank im Voraus:

`<html><body>

2023-10-25 08:33:07.953  - info: host.iobroker stopInstance system.adapter.panasonic-comfort-cloud.0 (force=false, process=true)
--
2023-10-25 08:33:07.960  - info: panasonic-comfort-cloud.0 (14552) Got terminate signal TERMINATE_YOURSELF
2023-10-25 08:33:07.961  - info: panasonic-comfort-cloud.0 (14552) cleaned everything up...
2023-10-25 08:33:07.962  - info: panasonic-comfort-cloud.0 (14552) terminating
2023-10-25 08:33:07.963  - info: panasonic-comfort-cloud.0 (14552) Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
2023-10-25 08:33:07.998  - info: host.iobroker stopInstance system.adapter.panasonic-comfort-cloud.0 send kill signal
2023-10-25 08:33:08.465  - info: panasonic-comfort-cloud.0 (14552) terminating
2023-10-25 08:33:08.526  - info: host.iobroker instance system.adapter.panasonic-comfort-cloud.0 terminated with code 11 (ADAPTER_REQUESTED_TERMINATION)
2023-10-25 08:33:11.096  - info: host.iobroker instance system.adapter.panasonic-comfort-cloud.0 started with pid 14591
2023-10-25 08:33:12.834  - info:  panasonic-comfort-cloud.0 (14591) starting. Version 2.2.4 (non-npm:  marc2016/ioBroker.panasonic-comfort-cloud#2a49eb563a6bf7623c8798ed359d18e57a3214fe)  in /opt/iobroker/node_modules/iobroker.panasonic-comfort-cloud, node:  v18.18.2, js-controller: 5.0.12
2023-10-25 08:33:13.093  - info: panasonic-comfort-cloud.0 (14591) state panasonic-comfort-cloud.0.info.connection changed: false (ack = true)
2023-10-25 08:33:13.156  - info: panasonic-comfort-cloud.0 (14591) Loaded app version from GitHub: 1.19.1
2023-10-25 08:33:14.403  - info: panasonic-comfort-cloud.0 (14591) Login successful.
2023-10-25 08:33:14.422  - info: panasonic-comfort-cloud.0 (14591) state panasonic-comfort-cloud.0.info.connection changed: true (ack = true)
2023-10-25 08:33:15.590  - error:  panasonic-comfort-cloud.0 (14591) Unknown error: TypeError: Cannot set  properties of undefined (setting 'guid'). Stack: TypeError: Cannot set  properties of undefined (setting 'guid')
at /opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:131:52
at arrayMap (/opt/iobroker/node_modules/lodash/lodash.js:653:23)
at Function.map (/opt/iobroker/node_modules/lodash/lodash.js:9622:14)
at /opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:129:49
at arrayMap (/opt/iobroker/node_modules/lodash/lodash.js:653:23)
at Function.map (/opt/iobroker/node_modules/lodash/lodash.js:9622:14)
at ComfortCloudClient. (/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:128:40)
at step (/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:33:23)
at Object.next (/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:14:53)
at fulfilled (/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:5:58)

</body>
</html>`

**Comment by hauthaler** [comment]
![1698438236024-1189bc96-6e01-4e0d-9602-4aca097c1362-grafik](https://github.com/marc2016/ioBroker.panasonic-comfort-cloud/assets/148943785/61689372-fbe7-432e-a0bc-cb768286705f)
![1698438173252-ced0cae1-bfbe-4717-92d5-b452ff318bc5-grafik](https://github.com/marc2016/ioBroker.panasonic-comfort-cloud/assets/148943785/641f9963-69ad-481e-9c2f-140b2df01149)

Kleine Ergänzung:
Ich habe den Adapter ganz normal über iobroker installiert, anschließend den Wert "1.19.1" im Feld "Neue Version der App für API" gesetzt.

**Comment by Skol6** [comment]
hab leider die gleichen Probleme. Gibts da schon eine Idee dazu?

**Comment by Stefan8485** [comment]
Ich habe heute den Adapter auf der Synology im Docker auch installiert und das selbige Problem, muss man im Docker noch einen weiteren Port für den Adapter öffnen? finde dazu in der Doc nichts.

**Comment by marc2016** [comment]
Das Problem von damals war erledigt.
Es scheint seit heute Nacht ein neues Problem zu geben. Schaue ich mir an. Ich selbst habe auch keine Verbindung mehr.

**Comment by marc2016** [comment]
Ich habe das Problem bei mir gefunden: ein Gerät hatte keine Internet Verbindung. In der aktuellen Version funktioniert dann der gesamte Adapter runter. Auf dem folgen Branch habe bin ich aktuell dabei auf den Gerät dann nur einen State zu setzen, so dass alle anderen Geräte weiterhin angesteuert werden können.
https://github.com/marc2016/ioBroker.panasonic-comfort-cloud/tree/connected-state

Ist das evtl bei euch auch der Fall? Oder habt ihr noch eine Wärmepumpe im Account eingebunden?

**Comment by Skol6** [comment]
Hi,

ich hab nur eine Wärmepumpe im Account drinnen.
Der Adapter läuft aber auf einer Synology über Docker -> könnte auch daran liegen.

Adapter meint er ist verbunden:
![image](https://github.com/marc2016/ioBroker.panasonic-comfort-cloud/assets/94216949/dcda6ae0-d7c1-44dc-8d19-84686c7327d2)

Fehlermeldung:
`Unknown error: TypeError: Cannot set properties of undefined (setting 'guid'). Stack: TypeError: Cannot set properties of undefined (setting 'guid') at /opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:131:52 at arrayMap (/opt/iobroker/node_modules/lodash/lodash.js:653:23) at Function.map (/opt/iobroker/node_modules/lodash/lodash.js:9622:14) at /opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:129:49 at arrayMap (/opt/iobroker/node_modules/lodash/lodash.js:653:23) at Function.map (/opt/iobroker/node_modules/lodash/lodash.js:9622:14) at ComfortCloudClient.<anonymous> (/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:128:40) at step (/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:33:23) at Object.next (/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:14:53) at fulfilled (/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:5:58)`

**Comment by Stefan8485** [comment]
Bei mir kommt das selbe raus wie bei skol6. 
auch das Setting ist gleich docker in synology.

**Comment by marc2016** [comment]
Eine Wärmepumpe lässt sich leider gar nicht mit dem Adapter abrufen und steuern. Ob wohl Klimaanlage und Wärmepumpe in einer App sind, werden die komplett unterschiedlich angesteuert. Ich hatte immer mal vor auch Wärmepumpen zu integrieren, aber besitze selber keine und Tests sind deswegen sehr umständlich.

**Comment by Stefan8485** [comment]
Das ist echt schade.
Wenn du jemanden zum testen brauchst, oder unterstützen brauchst :-) bin da :-)

**Comment by Skol6** [comment]
Ah verdammt. Ja das war mir natürlich nicht klar das das nur für Klimaanlagen geht.
Panasonic hängt je beide Geräte in die Comfort Cloud rein. Bau mir nächste Woche auch noch eine Panasonic Klimaanlage rein und würde natürlich alles gerne mit deinem Adapter steuern.
Kann dir aber gerne meinen Comfort Cloud Zugang senden dann kannst dich austoben :)

**Comment by Skol6** [comment]
ABER: hier beschreiben einige das sie mit deinem Adapter ihre Aquarea Wärmepumpe einwandfrei lesen und steuern können. Also ich trau dem Braten noch nicht ganz.
Könntest du dich mal testweise bei mir dranhängen? Wie schick ich dir eine Mail?
Ich fürchte eher das es an Docker liegt und nicht an deinem Adapter

**Comment by Skol6** [comment]
OK - ich sehe es ein.
Versuch deinerseits war mal da, aber es geht nicht viel weiter - https://github.com/marc2016/panasonic-aquarea-client

Die Panasonic Aquarea Community ist mittlerweile riesig. Wie können wir dir da helfen?

**Comment by Stefan8485** [comment]
ich hatte bei mir im log mal was gesehen heute früh von Port 9001, hab den geöffnet am docker aber das war ohne erfolg. Ich finde aber diese nicht mehr. oder ich habe mich getäuscht und es war ein anderer adapter, den hab heute Panasonic und Danfoss integrieren wollen.

**Comment by marc2016** [comment]
@Skol6 @Stefan8485 
Ich habe jetzt mal die Zeit gefunden mich weiter damit zu beschäftigen und habe ein Python Projekt gefunden, welches sich zu Aquara verbindet. Damit konnte ich meinen Client so erweitern, dass ich Geräte abrufen kann (denke ich) . Ich kann mich anmelden und eine leere Geräteliste abfragen, weil ich keine Wärmepumpe habe.

Ich habe habe ein kleines Skript geschrieben, mit dem man das testen kann. Dazu muss man das ppm Paket installieren und dann das Skript starten. Das sollte denke ich so gehen:

`npm i -g panasonic-aquarea-client

npx aquarea-client-cli`

Das erste installiert das Paket einmal global und der zweite Befehl für das Skript aus. Das sollte dann in der Kommandozeile so aussehen:
<img width="471" alt="Bildschirmfoto 2023-12-29 um 09 33 42" src="https://github.com/marc2016/ioBroker.panasonic-comfort-cloud/assets/18601365/f6717eb2-bfed-4d83-8cec-bc029e2d758a">

Unter Device sollte dann mindestens ein Gerät stehen.
Könnte das einer von euch testen? :-) Danach könnte ich weiter machen. Danke!

**Comment by Stefan8485** [comment]
@marc2016 
Bin erst gegen Abend am Rechner, da kann ich es aber gerne testen das wäre ja spitze. 
Muss eh noch meine neuen Shelly’s einbinden dann mach ich das mal parallel. 

Melde mich. Außer @Skol6  hat früher Zeit ;) 

Danke dir vielmals vorab. 

Stefan

**Comment by Skol6** [comment]
Hallo Mark, wie kann ich dir eine private Nachricht zusenden oder mail?
Dann schick ich dir einfach die Zugangsdaten - das hilft dir vermutlich viel mehr, da du direkt debuggen kannst.

**Comment by Stefan8485** [comment]
@marc2016 
Bei mir kommt das ganze zum Vorschein:

`? Select a package manager Get device
{
  accessToken: { token: 'aea2a86b-836d-418d-8ac6-6d683610a243' },
  device: [ { deviceGuid: 'B764948155', configration: [Array] } ],
  errorCode: 0`

**Comment by marc2016** [comment]
Das sieht schonmal gut aus. Der Login klappt und bei euch wird auch ein Gerät zurückgegeben. Dadrauf kann ich aufbauen. Mit den Zugangsdaten wäre es natürlich super :-D
Du könntest die an github@lammers.dev senden. 
Vielen Dank an euch beide!

**Comment by Skol6** [comment]
Hab die Zugangsdaten versendet. Bin gespannt was du Herausfindest.

**Comment by marc2016** [comment]
@Skol6 Vielen Dank für die Zugangsdaten. Hat super geklappt und ich konnte die Struktur der Antwort nachbauen. Ich versuche jetzt die Ansteuerung umzusetzen.

**Comment by marc2016** [comment]
Kurzes Update: Leider bin ich seit Anfang des Jahres beruflich sehr eingespannt und muss dadurch noch an einem anderen Projekt von mir weiter programmieren (für Stundenbuchungen). Deswegen geht es gerade nicht weiter. Ab dem kommenden Wochenende sollte es aber weitergehen.

**Comment by Stefan8485** [comment]
Servus Marc, wollte mal Nachfragen ob du schon einen Zeitpunkt nennen kannst für ein Updates für diesen Issue?

Gruss Stefan
