### ISSUE TITLE
kein Log In mehr möglich

### ISSUE THREAD

**Issue by MrP646** [marc2016/ioBroker.panasonic-comfort-cloud#55]
Hallo zusammen,

leider funktioniert seit ein paar Tagen der Adapter nicht mehr.
Die Android App wurde auf 1.20.0 geändert und es wird eine 2 Faktoren Authentifizierung per SMS durchgeführt.
Das Protokoll gibt folgende Fehlermeldung aus:
`Service error: Request failed with status code 401
Login ID or password is incorrect,or account is locked. Code=4101. Stack: ServiceError: Request failed with status code 401
Login ID or password is incorrect,or account is locked
    at new ServiceError (/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/model/ServiceError.js:23:28)
    at ComfortCloudClient.handleError (/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:193:31)
    at ComfortCloudClient.<anonymous> (/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:107:30)
    at step (/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:33:23)
    at Object.throw (/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:14:53)
    at rejected (/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:6:65)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)`

Am Handy ist das Einloggen möglich.

Mache ich hier was falsch?
Danke für die Hilfe!

**Comment by MrP646** [comment]
Merkwürdig, nach allen möglichen Versuchen ist der Adapter wieder eingeloggt. Lag also an mir.
