### ISSUE TITLE
Zwei Faktor Authentifizierung

### ISSUE THREAD

**Issue by t1m02k16** [marc2016/ioBroker.panasonic-comfort-cloud#57]
Grüße,
leider ist jetzt eine Zwei Faktor Authentifizierung pflicht :(
Somit bin ich nicht mehr in der Lage mich anzumelden....

**Comment by mtb-z** [comment]
Ist bei mir leider ebenso. Folgende Fehlermeldung wird im ioBroker Log ausgegeben: 

`Service error: Request failed with status code 401Login ID or password is incorrect,or account is locked. Code=4101. Stack: ServiceError: Request failed with status code 401Login ID or password is incorrect,or account is locked at new ServiceError (/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/model/ServiceError.js:23:28) at ComfortCloudClient.handleError (/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:193:31) at ComfortCloudClient.<anonymous> (/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:107:30) at step (/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:33:23) at Object.throw (/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:14:53) at rejected (/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:6:65) at process.processTicksAndRejections (node:internal/process/task_queues:95:5)`

**Comment by t1m02k16** [comment]
@marc2016 kannst du uns hier helfen?

**Comment by marc2016** [comment]
Hallo,
ich bin bisher noch nicht auf das Problem gestoßen. Ich habe zwei Accounts und mit beiden kann ich mich in der App und im Adapter anmelden. Muss die Zwei Faktor Authentifizierung irgendwo aktivieren?

**Comment by t1m02k16** [comment]
Sorry Marc, bei dem Acccout welchen ich für iobroker nutze, habe ich keine Zwei Faktor Authentifizierung. Der Adapter hat sich nicht verbunden und das lag daran, dass ich lediglich das Passwort erneut eingeben musste

**Comment by mtb-z** [comment]
Bei mir ist mit dem Update auf 3.0 auch wieder alles ok. Vielen Dank!
