### ISSUE TITLE
Verbindung nicht mehr möglich. Verschieden Fehlermeldung

### ISSUE THREAD

**Issue by superemil70** [marc2016/ioBroker.panasonic-comfort-cloud#58]
Seit ein Paar Tage kommen ständig Fehlermeldung und der Adapter ist nicht nutzbar

Genutzt wird er Adapter mit Version 2.3.0 und API 1.20.1

Bis jetzt diese Meldungen
`panasonic-comfort-cloud.0
	2024-05-15 19:12:46.033	error	Service error when connecting to device Klima Wohnzimmer: 
	Request failed with status code 500Adapter internal error. Code=5006. Stack: ServiceError: 
	Request failed with status code 500Adapter internal error at new ServiceError (/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/model/ServiceError.js:23:28) 
	at ComfortCloudClient.handleError (/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:193:31)
	at ComfortCloudClient.<anonymous> (/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:172:30) 
	at step (/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:33:23) 
	at Object.throw (/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:14:53) 
	at rejected (/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:6:65)
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)`

`panasonic-comfort-cloud.0
	2024-05-16 21:52:29.767	error	Service error: Request failed with status code 429undefined. Code=undefined. 
	Stack: ServiceError: Request failed with status code 429undefined at new ServiceError 
	(/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/model/ServiceError.js:23:28) 
	at ComfortCloudClient.handleError (/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:193:31) 
	at ComfortCloudClient.<anonymous> (/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:228:30)
	at step (/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:33:23) 
	at Object.throw (/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:14:53) 
	at rejected (/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:6:65) 
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)`

Hat noch jemand dieses Problem??

**Comment by superemil70** [comment]
Hat sich erledigt. Fehler lag an meinem geänderten Blockly
