### ISSUE TITLE
Cannot set properties of undefined (setting 'guid').

### ISSUE THREAD

**Issue by filiprozanski** [marc2016/ioBroker.panasonic-comfort-cloud#60]
**Describe the bug**  
The adapter breaks right after successful login.

I have single device in my Aquarea Smart Cloud, a heat pump. After I configured the adapter, it was able to successfully log in, but then it threw an error:

panasonic-comfort-cloud.0
2024-07-16 13:53:31.487	error	Unknown error: TypeError: Cannot set properties of undefined (setting 'guid'). Stack: TypeError: Cannot set properties of undefined (setting 'guid') at /opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:97:40 at arrayMap (/opt/iobroker/node_modules/lodash/lodash.js:653:23) at Function.map (/opt/iobroker/node_modules/lodash/lodash.js:9622:14) at /opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:95:54 at arrayMap (/opt/iobroker/node_modules/lodash/lodash.js:653:23) at Function.map (/opt/iobroker/node_modules/lodash/lodash.js:9622:14) at ComfortCloudClient.getGroups (/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:94:49) at process.processTicksAndRejections (node:internal/process/task_queues:95:5) at async PanasonicComfortCloud.onReady (/opt/iobroker/node_modules/iobroker.panasonic-comfort-cloud/build/main.js:72:24)

panasonic-comfort-cloud.0
2024-07-16 13:53:30.235	info	Login successful.

**To Reproduce**  
There are no specific steps really, I have clean instance of local, docker hosted, iobroker, with this adapter being the first one I installed.

**Expected behavior**  
For adapter to map my device as an object.

**Screenshots & Logfiles**  
Already provided above in the description

**Versions:**  
 - Adapter version: 3.0.2
 - JS-Controller version: 4.0.24
 - Node version: v18.17.1
 - Operating system: default iobroker container from docker hub

**Additional context**

**Comment by sailor25462** [comment]
I would second this issue. I have the same log error in my installation. Node-js 20.17.0
