### ISSUE TITLE
V3.0.3 gives me "Service error: Request failed with status code 401 "

### ISSUE THREAD

**Issue by Scram99** [marc2016/ioBroker.panasonic-comfort-cloud#68]
![Bildschirmfoto vom 2024-11-10 11-19-51](https://github.com/user-attachments/assets/2924da6f-6bfe-4c7f-a5ca-b3d1aece7e07)

Dunno what i'm doing wrong. Installed 3.0.3 and still get:
Service error: Request failed with status code 401 New version app has been published. Code=4106. Stack: ServiceError: Request failed with status code 401 New version app has been published at ComfortCloudClient.handleError (/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:149:31) at ComfortCloudClient.login (/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:68:18) at process.processTicksAndRejections (node:internal/process/task_queues:95:5) at async PanasonicComfortCloud.onReady (/opt/iobroker/node_modules/iobroker.panasonic-comfort-cloud/build/main.js:65:9)

Also tried to enter credentials again. Does not work for me.

**Comment by Scram99** [comment]
Manually updating APP Version to 1.22.0 helps here :-)
